// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Train.EFCore.API.Data;

#nullable disable

namespace Train.EFCore.API.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20251113194713_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Train.EFCore.API.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Musical"
                        },
                        new
                        {
                            Id = 16,
                            Name = "War"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sport"
                        });
                });

            modelBuilder.Entity("Train.EFCore.API.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeRating")
                        .HasColumnType("int");

                    b.Property<int>("MainGenreId")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<string>("Synopsis")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Plot");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("MainGenreId");

                    b.ToTable("Pictures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRating = 18,
                            MainGenreId = 12,
                            ReleaseDate = "19991015",
                            Synopsis = "An insomniac office worker and a soap maker form an underground fight club.",
                            Title = "Fight Club"
                        });
                });

            modelBuilder.Entity("Train.EFCore.API.Models.Movie", b =>
                {
                    b.HasOne("Train.EFCore.API.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("MainGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Train.EFCore.API.Models.Person", "Actors", b1 =>
                        {
                            b1.Property<int>("MovieId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("FirstName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MovieId", "Id");

                            b1.ToTable("Movie_Actors", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MovieId");

                            b1.HasData(
                                new
                                {
                                    MovieId = 1,
                                    Id = 1,
                                    FirstName = "Brad",
                                    LastName = "Pitt"
                                },
                                new
                                {
                                    MovieId = 1,
                                    Id = 2,
                                    FirstName = "Edward",
                                    LastName = "Norton"
                                },
                                new
                                {
                                    MovieId = 1,
                                    Id = 3,
                                    FirstName = "Helena",
                                    LastName = "Bonham Carter"
                                });
                        });

                    b.OwnsOne("Train.EFCore.API.Models.Person", "Director", b1 =>
                        {
                            b1.Property<int>("MovieId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MovieId");

                            b1.ToTable("Movie_Directors", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MovieId");

                            b1.HasData(
                                new
                                {
                                    MovieId = 1,
                                    FirstName = "David",
                                    LastName = "Fincher"
                                });
                        });

                    b.Navigation("Actors");

                    b.Navigation("Director");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Train.EFCore.API.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
